- name: K8S common tasks
  hosts: all
  become: true
  roles:
    - role: common
      vars:
        version: stable
        install_packages:
          - net
          - prof
          - tools
        disks:
          - dev: /dev/sda
            mount: /mnt/data
            fs: ext4
            role: data

- name: Join worker nodes to K8S cluster
  hosts: all
  become: true
  roles:
    - role: worker
