- name: K8S control node initialization play
  hosts: all
  become: true
  roles:
    - role: k8s_control
      vars:
        k8s_control_version: stable
        k8s_control_install_packages:
          - net
          - prof
          - tools
        k8s_control_disks:
          - dev: /dev/sda
            mount: /mnt/data
            fs: ext4
            role: data
