name: Terraform modules validation
run-name: ${{ github.ref_name}} validation
on: [ push, pull_request ]

jobs:
  validate-modules:
    name: Validate and test modules

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        module:
        - pve_pool

    defaults:
      run:
        working-directory: ./modules/${{ matrix.module }}

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Initialize module ${{ matrix.module }}
      run: terraform init

    - name: Validate module ${{ matrix.module }}
      run: terraform validate

    - name: Run tests in module ${{ matrix.module }}
      run: terraform test
