- name: Install packages in category
  ansible.builtin.package:
    name: '{{ package }}'
    state: present
  loop: '{{ categories[category] }}'
  loop_control:
    loop_var: package
  vars:
    categories:
      net:
        - iproute2-ss
        - netcat-openbsd
        - bind-tools
        - iftop
        - nethogs
        - iptraf-ng
        - tcpdump
        - tshark
      prof:
        - btop
        - nethogs
        - procps
        - iotop
        - bpftrace
